# Generated by Django 5.0.2 on 2024-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecom', '0002_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='app_ecom.product'),
        ),
    ]
